import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Message } from './message.entity';
import { ChatService } from './chat.service';
import { ChatController } from './chat.contorller';

@Module({
  imports: [TypeOrmModule.forFeature([Message])],
  //   If you want to use the repository outside of the module
  //   which imports TypeOrmModule.forFeature,
  //   you'll need to re-export the providers generated by it.
  //   You can do this by exporting the whole module, like this:
  exports: [TypeOrmModule],
  providers: [ChatService],
  controllers: [ChatController],
})
export class ChatModule {}
